kind = "web"
previewPath = "/"
title = "Nexus Oracle Tradepro"
version = "1.0.0"
id = "artifacts/nexus-oracle"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19256

[services.development]
run = "pnpm --filter @workspace/nexus-oracle run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nexus-oracle", "run", "build" ]
publicDir = "artifacts/nexus-oracle/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19256"
BASE_PATH = "/"
